# Generated by Django 4.2.6 on 2023-10-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registroempresas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuarios',
            name='password',
            field=models.CharField(max_length=600),
        ),
    ]
